### ISSUE TITLE
New version 1.4 and old version is 3.3

### ISSUE THREAD

**Issue by romildo** [madmaxms/theme-jade-1#1]
Why did the version number go from v3.3 to v1.4 in the latest release?

**Comment by madmaxms** [comment]
This is because I changed the versioning scheme. From now on the major version number will stay at 1 and will only be increased if there are very major changes to the theme or backward compatibility gets lost. But in this case I would create an entire new project ("Jade-2" or stg.) where the versioning will start with 2.0 and which will coexist with Jade-1.
